services:
  # Relational DB for Ledger & Transactions
  db:
    image: postgres:15-alpine
    container_name: payment-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  # Idempotency & Caching
  redis:
    image: redis:7-alpine
    container_name: payment-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - payment_redis_data:/data

  # Orchestrator Application
  app:
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=500
    ports:
      - "8080:3000" # Access at http://localhost:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npx knex migrate:latest && npx tsx watch src/index.ts"
    container_name: orchestrator-api
    restart: always
    depends_on:
      - db
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: payment-metrics
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    depends_on:
      - app
  
  grafana:
    image: grafana/grafana:latest
    container_name: payment-dashboard
    ports:
      - "3001:3000" # Access at http://localhost:3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - payment_grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  localstack:
    container_name: aws-emulator
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,rds,elasticache,ecs,ec2
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./localstack:/var/lib/localstack"

# Persistent Storage
volumes:
  payment_db_data:
  payment_redis_data:
  payment_grafana_data: